duck_assistant:
    resource: "@DuckAssistantBundle/Resources/config/main.yml"
    prefix:   /

duck_assistant_categories:
    resource: "@DuckAssistantBundle/Resources/config/cat.yml"
    prefix:   /cat

duck_assistant_users:
    resource: "@DuckAssistantBundle/Resources/config/user.yml"
    prefix:   /user

duck_assistant_tasks:
    resource: "@DuckAssistantBundle/Resources/config/task.yml"
    prefix:   /task

login_action:
    path:     /login
    defaults: { _controller: DuckAssistantBundle:Login:login }

login_check:
    path:     /login_check
    defaults: { _controller: DuckAssistantBundle:Login:loginCheck }

logout:
  path:     /logout