duck_assistant:
    resource: "@DuckAssistantBundle/Resources/config/main.yml"
    prefix:   /

duck_assistant_categories:
    resource: "@DuckAssistantBundle/Resources/config/cat.yml"
    prefix:   /cat

duck_assistant_users:
    resource: "@DuckAssistantBundle/Resources/config/user.yml"
    prefix:   /user

duck_assistant_tasks:
    resource: "@DuckAssistantBundle/Resources/config/task.yml"
    prefix:   /task

duck_assistant_Product:
    resource: "@DuckAssistantBundle/Resources/config/product.yml"
    prefix:   /product
duck_assistant_Shop:
    resource: "@DuckAssistantBundle/Resources/config/shop.yml"
    prefix:   /shop

duck_assistant_Price:
    resource: "@DuckAssistantBundle/Resources/config/price.yml"
    prefix:   /price

login_action:
    path:     /login
    defaults: { _controller: DuckAssistantBundle:Login:login }

login_check:
    path:     /login_check
    defaults: { _controller: DuckAssistantBundle:Login:loginCheck }

logout:
  path:     /logout