security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~

       
        secured_area:
                     logout:
                         path:   /logout
                         target: /


    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    providers:
            in_memory:
                memory:
                    users:
                        efik:
                            password: efik
                            roles: 'ROLE_USER'
                        ucze:
                            password: ucze
                            roles: 'ROLE_USER'
                        admin:
                            password: admin
                            roles: 'ROLE_ADMIN'