security:

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            provider: administrators
            form_login:
                  login_path: /login
                  check_path: /login_check
            logout:
                  path:   /logout
                  target: /

    access_control:
         - { path: ^/cat/add, roles: ROLE_USER }
         - { path: ^/cat/edit, roles: ROLE_USER }
         - { path: ^/cat/del, roles: ROLE_USER }
         - { path: ^/task/add, roles: ROLE_USER }
         - { path: ^/task/edit, roles: ROLE_USER }
         - { path: ^/task/del, roles: ROLE_USER }
         - { path: ^/user/add, roles: ROLE_USER }
         - { path: ^/user/edit, roles: ROLE_USER }
         - { path: ^/user/del, roles: ROLE_USER }


    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            Duck\AssistantBundle\Entity\User: plaintext

    providers:
            administrators:
                entity:
                    class: DuckAssistantBundle:User
                    property: name
            in_memory:
                memory:
                    users:

                        admin:
                            password: admin
                            roles: 'ROLE_ADMIN'