# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  duck_assistantbundle.lists.listprovider:
      class: Duck\AssistantBundle\lists\ListProvider
      arguments: [ @doctrine.orm.default_entity_manager, @security.token_storage ]

  doctrine.user_listener:
    class: Duck\AssistantBundle\EventListener\EntityAuthor
    tags:
      - { name: doctrine.event_listener, event: prePersist, method: prePersist }
    arguments:
      - "@security.token_storage"